version = "3.10.4"
runner.dialect = scala3
maxColumn = 140

lineEndings = unix
assumeStandardLibraryStripMargin = true

project.includePaths = [
  "glob:**/*.scala",
  "glob:**/*.md"
]


indent {
  defnSite = 2
  matchSite = 2
  caseSite = 5
  extendSite = 2
}

align = more
align {
  stripMargin = true
  tokens = ["=", "=>", "->"]
  arrowEnumeratorGenerator = true
}

newlines {
  source = keep
  topLevelStatementBlankLines = []
  topLevelBodyIfMinStatements = []
  forceBeforeMultilineAssign = def
  implicitParamListModifierPrefer = before
  avoidForSimpleOverflow = [tooLong, punct]
  avoidInResultType = true
  inInterpolation = avoid
}
danglingParentheses.preset = true

rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  PreferCurlyFors,
  SortModifiers
]

rewrite.trailingCommas.style = always

rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = true

spaces {
  beforeContextBoundColon = never
  inImportCurlyBraces = true
  inInterpolatedStringCurlyBraces = false
  inParentheses = false
  afterKeywordBeforeParen = true
  afterSymbolicDefs = false
}
